language: csharp
solution: dotAPNS.sln
dotnet: 3.1
mono: none
addons:
    apt:
        packages:
            - dotnet-sdk-2.1
before_install:
    - echo "$dotapns_tests_p8_contents" > "jwt.p8"
script:
    - dotnet build ./dotAPNS/dotAPNS.csproj --framework netstandard2.0
    - dotnet build ./dotAPNS/dotAPNS.csproj --framework netstandard2.1
    - dotnet build ./dotAPNS.AspNetCore/dotAPNS.AspNetCore.csproj
    - dotnet build ./dotAPNS.Tests/dotAPNS.Tests.csproj --framework netcoreapp2.1
    - dotnet build ./dotAPNS.Tests/dotAPNS.Tests.csproj --framework netcoreapp3.1
    - dotnet test ./dotAPNS.Tests/dotAPNS.Tests.csproj --framework netcoreapp2.1
    - dotnet test ./dotAPNS.Tests/dotAPNS.Tests.csproj --framework netcoreapp3.1